#ifndef _CXCORE_INTERNAL_H_
#define _CXCORE_INTERNAL_H_
#include "cxcore.h"
#include "cxmisc.h"
#include <math.h>
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <limits.h>
#include <float.h>
#endif /*_CXCORE_INTERNAL_H_*/
